# Generated by Django 3.2 on 2022-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_liketweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='0', max_length=140),
            preserve_default=False,
        ),
    ]
